DELETE http://localhost:3000/update/5
Content-Type: application/json

{
   "id": "4"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
   {
    "first_name": "John",
    "middle_name": "M.",
    "last_name": "Peter",
    "DOB": "20-05-2000",
    
    "username": "john",
    "password": "john"
}
}
###

POST http://localhost:3000/roles
Content-Type: application/json

{
    "Roles": "Voter"
}

